env:
  global:
    - Features=use-mock-routing
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
sudo: false
branches:
  only:
    - master
    - dev
cache:
  cargo: true
before_script:
  - (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update
  - (which rustfmt && cargo install-update rustfmt) || cargo install rustfmt
  - (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
script:
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
        (
            set -x;
            echo "--- Check format ---" &&
            cd ffi_utils &&
            cargo fmt -- --write-mode=diff &&
            cd ../safe_core &&
            cargo fmt -- --write-mode=diff &&
            cd ../safe_app &&
            cargo fmt -- --write-mode=diff &&
            cd ../safe_authenticator &&
            cargo fmt -- --write-mode=diff &&
            echo "--- Test ffi_utils ---" &&
            cd ../ffi_utils &&
            cargo test  --verbose --release &&
            echo "--- Check compilation against actual routing ---" &&
            cd ../safe_core &&
            cargo rustc --verbose --release &&
            cargo rustc --verbose --release -- --test -Zno-trans &&
            cd ../safe_app &&
            cargo rustc --verbose --release -- --test -Zno-trans &&
            cd ../safe_authenticator &&
            cargo rustc --verbose --release -- --test -Zno-trans &&
            echo "--- Test against mock ---" &&
            cd ../safe_core &&
            cargo test --verbose --release --features "$Features" &&
            cd ../safe_app &&
            cargo test --verbose --release --features "$Features" &&
            cd ../safe_authenticator &&
            cargo test --verbose --release --features "$Features";
        );
    else
        (
            set -x;
            curl -sSL -o run_clippy.sh https://github.com/maidsafe/QA/raw/master/bash_scripts/travis/run_clippy.sh &&

            cd ffi_utils && unset Features && bash ../run_clippy.sh && export Features=use-mock-routing &&
            cd ../safe_core && bash ../run_clippy.sh &&
            cd ../safe_app && bash ../run_clippy.sh &&
            cd ../safe_authenticator && bash ../run_clippy.sh;
        );
    fi
before_cache:
  - cargo prune
