vars:
  - &stable "1.26.1"
  - &stable-i686 "1.26.1-i686-unknown-linux-gnu"
  - &nightly "nightly-2018-05-29"
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_STABLE=1.26.1
    - RUST_NIGHTLY=nightly-2018-05-29
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
language: rust
stages:
  - stable
  - nightly-warmup
  - nightly-tests
jobs:
  allow_failures:
    - rust: *stable-i686
  include:
    # Stable
    - stage: stable
      script: set -x; scripts/stable
      os: linux
      rust: *stable
    - os: linux
      script: set -x; scripts/stable
      rust: *stable-i686
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: osx
      script: set -x; scripts/stable
      rust: *stable
    # Nightly compiler warm-up + clippy
    - stage: nightly-warmup
      script: set -x; scripts/build-all
      os: linux
      rust: *nightly
    - script: set -x; scripts/check-debug-ffi-utils && scripts/clippy-ffi-utils && scripts/check-debug-real && scripts/clippy-real
      if: type = pull_request
      os: linux
      rust: *nightly
    # Nightly tests + clippy
    - stage: nightly-tests
      script: set -x; scripts/test-all
      os: linux
      rust: *nightly
    - script: set -x; scripts/check-debug-mock && scripts/clippy-mock
      if: type = pull_request
      os: linux
      rust: *nightly
sudo: false
cache:
  cargo: true
before_script:
  # Expected version change PR title format:
  # Version change: safe_app to 0.2.2; safe_authenticator to 0.2.3; safe_core to 0.26.0;
  - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ [Vv]ersion[[:space:]]change.*safe_authenticator[[:space:]]to[[:space:]]([^;]+) ]]; then
      SAFE_AUTHENTICATOR_VERSION=v$(cargo pkgid --manifest-path=safe_authenticator/Cargo.toml | sed -e "s/.*[:#]\(.*\)/\1/");
      if [[ "v${BASH_REMATCH[1]}" != $SAFE_AUTHENTICATOR_VERSION ]]; then
        echo "Version mismatch between commit message and Cargo.toml for safe_authenticator.";
        false;
      fi;
    else
      SAFE_AUTHENTICATOR_VERSION=${TRAVIS_COMMIT:0:7};
    fi
  - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ [Vv]ersion[[:space:]]change.*safe_app[[:space:]]to[[:space:]]([^;]+) ]]; then
      SAFE_APP_VERSION=v$(cargo pkgid --manifest-path=safe_app/Cargo.toml | sed -e "s/.*[:#]\(.*\)/\1/");
      if [[ "v${BASH_REMATCH[1]}" != $SAFE_APP_VERSION ]]; then
        echo "Version mismatch between commit message and Cargo.toml for safe_app.";
        false;
      fi;
    else
      SAFE_APP_VERSION=${TRAVIS_COMMIT:0:7};
    fi
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - if [ "$TRAVIS_RUST_VERSION" = $RUST_NIGHTLY ] && [ "$TRAVIS_OS_NAME" = linux ]; then
      bash cargo_install.sh rustfmt-nightly 0.8.2;
      bash cargo_install.sh clippy 0.0.206;
    fi
after_script:
  - if [[ $TRAVIS_EVENT_TYPE = pull_request && -n $(git diff --shortstat 2> /dev/null | tail -n1) ]]; then
      echo "Working tree is dirty after building.  Probably Cargo.lock should be updated.";
      git status;
      travis_terminate 1;
    fi
before_cache:
  - cargo prune
before_deploy:
  - bash cargo_install.sh cargo-script 0.2.8
  - mkdir -p target/deploy
  # Build for mock.
  - ./scripts/package.rs --lib --name safe_app -d target/deploy --mock
  - ./scripts/package.rs --lib --name safe_authenticator -d target/deploy --mock
  # Build for production.
  - ./scripts/package.rs --lib --name safe_app -d target/deploy
  - ./scripts/package.rs --lib --name safe_authenticator -d target/deploy
deploy:
  provider: s3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: qEDay6TCAy3tBLqLYFOx9OjAdoRl010paK2//teFETfwUfJA/RtNSfkp1yrgx+kZ3FO8cthdDnwR3zjM3pkCL+5mGkQMAgvRY7rcEB5H1VyO4jkZRoB4n/yUu5jB4dHdeeRWTOJxNOOPA0G1Q65LLkJql2JGoJatqE3pBmJm0X8=
  bucket: safe-client-libs
  local-dir: target/deploy
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: $TRAVIS_RUST_VERSION =~ $RUST_STABLE && $TRAVIS_EVENT_TYPE = push
after_deploy: rm -rf target/deploy
