environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable

branches:
  only:
    - master
    - dev

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

build_script:
  - |-
    cd ffi_utils && cargo build --verbose --release
    cd ..\safe_core && cargo rustc --verbose --release --features testing -- --test -Zno-trans
    cd ..\safe_app && cargo rustc --verbose --release --features testing -- --test -Zno-trans
    cd ..\safe_authenticator && cargo rustc --verbose --features testing --release -- --test -Zno-trans

test_script:
  - |-
    cd ..\ffi_utils && cargo test --verbose --release
    cd ..\safe_core && cargo test --verbose --release --features "use-mock-routing testing"
    cd ..\safe_app && cargo test --verbose --release --features "use-mock-routing testing"
    cd ..\safe_authenticator && cargo test --verbose --release --features "use-mock-routing testing"
