environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - |-
    cd ffi_utils && cargo check --verbose --release --lib --tests
    cd ..\safe_core && cargo check --verbose --release --features testing --lib --tests
    cd ..\safe_app && cargo check --verbose --release --features testing --lib --tests
    cd ..\safe_authenticator && cargo check --verbose --features testing --release --lib --tests

test_script:
  - |-
    cd ..\ffi_utils && cargo test --verbose --release
    cd ..\safe_core && cargo test --verbose --release --features "use-mock-routing testing"
    cd ..\safe_app && cargo test --verbose --release --features "use-mock-routing testing"
    cd ..\safe_authenticator && cargo test --verbose --release --features "use-mock-routing testing"
