[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://docs.maidsafe.net/safe_core/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_client"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.22.0"

[workspace]
members = ["ffi_utils", "safe_app", "safe_core"]

[dependencies]
clippy = { version = "=0.0.99", optional = true }
ffi_utils = { path = "ffi_utils" }
futures = "~0.1.6"
lazy_static = "~0.2.1"
log = "~0.3.6"
maidsafe_utilities = "~0.10.0"
# routing = "~0.27.1"
routing = { git = "https://github.com/madadam/routing.git", branch = "mutable-data" }
rust_sodium = "~0.1.2"
rustc-serialize = "~0.3.22"
safe_app = { path = "safe_app" }
safe_core = { path = "safe_core" }
tokio-core = "~0.1.1"
unwrap = "~1.1.0"

[dev-dependencies]
crossbeam = "~0.2.10"
docopt = "~0.6.86"
regex = "~0.1.80"

[[example]]
bench = false
test = true
name = "email_stress_test"

[[example]]
bench = false
test = true
name = "client_stress_test"

[[example]]
bench = false
test = true
name = "self_authentication"

[[example]]
bench = false
test = true
name = "nfs_api"

[[example]]
bench = false
test = true
name = "simulate_browser"

[[example]]
bench = false
test = true
name = "email"

[features]
use-mock-routing = ["safe_app/use-mock-routing", "safe_core/use-mock-routing"]

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
name = "safe_core"
